### ISSUE TITLE
Giraffe back-end version

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-BookStore#196]
This repo should also be about showing alternatives to the "default" stack. A version of this repository that illustrates Giraffe instead of Suave for the back end *should* be relatively simple to do (I say that having not much experience in Giraffe at all!).

Perhaps this could be done as a fork from this repository - that way we could pull changes to the front end etc. into it in the future. What do others think of the best way to manage this?

**Comment by isaacabraham** [comment]
cc: @dustinmoris

**Comment by cartermp** [comment]
Would the name change?  Suave Azure Fable-Elmish.Giraffe is a bit much to say in one setting 😄.

On a more serious note, a fork of this repo using Giraffe (and a fork using Freya) are good ideas, especially since it can highlight the pluggable nature of using these libraries.  Wouldn't think it to be too difficult, since it seems like most of the activity here (and in the future) is on the front-end rather than the backend.

**Comment by forki** [comment]
We already talked about building a COVFEFE stack. Just need to find
matching tech

Am 03.10.2017 16:23 schrieb "Phillip Carter" <notifications@github.com>:

Would the name change? Suave Azure Fable-Elmish.Giraffe is a bit much to
say in one setting 😄.

On a more serious note, a fork of this repo using Giraffe (and a fork using
Freya) are good ideas, especially since it can highlight the pluggable
nature of using these libraries. Wouldn't think it to be too difficult,
since it seems like most of the activity here (and in the future) is on the
front-end rather than the backend.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SAFE-Stack/SAFE-BookStore/issues/196#issuecomment-333858332>,
or mute the thread

**Comment by isaacabraham** [comment]
@cartermp nope, it wouldn't. As you say, SAFE is about more than just the four techs in the name - it's more about a philosophy of functional-first programming across the stack, wherever possible, and taking advantage of features to make compelling apps in minimum effort.

The "S" actually stands for the Suave *model* - we always had in mind that Giraffe would play a key role as well. And, as you say, Freya can also join the party. Having an app like this shown with all three server tech would be super useful.

**Comment by dustinmoris** [comment]
Guys I can have a look at doing this for Giraffe. I'll try to get some time on it over the next few evenings and let you know how it goes.

**Comment by jhoerr** [comment]
I would benefit greatly from a Giraffe example. I am excited to use the SAFE stack but between a lack of familiarity with Paket and VS Code I'm hitting a wall trying to swap out the Suave parts for Giraffe.

**Comment by isaacabraham** [comment]
@jhoerr Are you using .NET "Full" or .NET Core?

**Comment by jhoerr** [comment]
@isaacabraham I’m using .NET Core.

**Comment by boyedarat** [comment]
@dustinmoris any luck with getting this to work with Giraffe?
Gracias!

**Comment by voronoipotato** [comment]
the Gafe stack, pronounced "Safe"

**Comment by Krzysztof-Cieslak** [comment]
Nah, S is back ;]
