### ISSUE TITLE
How to promote F# (emphasis on the business perspective)

### ISSUE THREAD

**Issue by oscarvarto** [SAFE-Stack/SAFE-BookStore#266]
Hi!

My name is Oscar Vargas Torres, and I work as a developer in Jalisco, México. .NET (read C#) is a very important Development Platform here in my country, and I guess it is one of the mainstream technologies around the world too.

I want to promote F# as a general purpose language. But my hunch is that focusing (only) on technical reasons to choose F# over other alternatives (say C#) is not going to be the best approach to get attention from investors and business people.

Lots of people think this way: "If C# can solve the problem, why bother learning something else? Choosing technologies with fewer trained people is a business risk".

So, I would like to approach this, not only from the technical perspective, but from a **business** perspective.

Can you (F# community member), share your thoughts so that, as a community, can provide convincing arguments for people that take business decisions?

Can you share success stories using F# in the industry (say Healthcare, Finance, Analytics, Retailer, e-commerce, automotive, etc.)? Why choosing F# was a wise decision over other technologies?

In the future, will F# become a better alternative, more than it is now? Why?

Full Stack Development with F# is possible with SAFE-Stack. That's why I am asking here. Because it is a compelling solution for a very common use case in our industry. Asking for help from the awesome F# community...

**Comment by isaacabraham** [comment]
@oscarvarto Hey Oscar. I'd say that some of this goes outside the scope of SAFE but the usual arguments around F# on .NET can be used. There are many great sites that spend more time on this e.g. [fsharp.org](http://fsharp.org/testimonials/) has many good testimonials and reasons for using F#. For example, a commonly used large-scale implementation of an e-commerce web platform in F# is Jet.com, but there are lots of others.

In the case of SAFE, we wanted to have an end-to-end web stack in F# that didn't have to compromise on giving up some of F#'s unique features to fit in with an existing framework or library - which means that you can re-use your F# skills across the stack instead of mixing with C# or Typescript etc. You can also read more [here](https://compositional-it.com/blog/2017/09-22-safe-release/index.html) - we're planning on moving this to the SAFE site, too.

**Comment by oscarvarto** [comment]
Hi @isaacabraham 

Thanks for taking some of your time to write something. I know that my question is out of the scope of SAFE, sorry. I don't know where else I can ask and get the answers registered, so that other people can benefit.

And even if there is already information on the subject, for example, the http://fsharp.org/testimonials/ you linked above, I guess that things keep moving, maybe a lot faster than in the past. For example, some days ago, I read this tweet from Miguel de Icaza:

http://bit.ly/2mrCEo3

That is awesome news for the F# community. I think that could bring more traction to F# (even if it does not use the SAFE approach).
I will keep digging more to be able to provide convincing arguments myself.

Thanks again!

**Comment by isaacabraham** [comment]
There's also the slack channels and twitter - see fsharp.org for the links - that might give you more information!
